set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER mips64-elf-gcc)
set(CMAKE_CXX_COMPILER mips64-elf-g++)
set(CMAKE_ASM_COMPILER mips64-elf-gcc)

set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)

set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)